# Introduction to Julia

Julia is a high-level programming language for technical computing which allows you to manipulate and analyse large data sets

## Interesting features:
 * Julia is build from the ground for techical computing. 
 * The language is close to the mathematical notation, for example to define a function $f(x) = 2x + 3$ in Julia is:

```julia
f(x) = 2x + 3
```
  
 * Julia is free and open-source software.
 * Julia's code is compiled to machine code and loops can be as fast as in other compiled languages (like Fortran or C).


## Instructions for installing Julia on your laptop

1. Go to http://julialang.org/downloads/ and follow the instructions.
2. Install one editors with support for Julia (such as [Juno](http://junolab.org/), notepad++, emacs... or even vim)

### Ways to run Julia:

#### Command line

* Use the `Tab` key to complete file, variable and function names
* `Up` and `down arrows` key to repeat a previously entered command
* `Control-R` to search a command
* On Windows enable "[quick edit](https://www.tekrevue.com/tip/boost-productivity-quickedit-mode-windows-command-prompt/)" for easier copy and pasting
![cmd](Images/julia-commandline.png)

#### Jupyter notebook (web-browser)

* Web-interface for Julia (among others)
* The Julia package `IJulia` which also installs Jupyter http://jupyter.org/
* Various [keyboard shortcuts](https://www.cheatography.com/weidadeyue/cheat-sheets/jupyter-notebook/) are defined to be productive with jupyter notebooks
* General documentation of [Jupyter Notebooks](http://jupyter-notebook.readthedocs.io)

![cmd](Images/julia-jupyter.png)

Text can be formatted using [markdown](https://en.wikipedia.org/wiki/Markdown).

#### Markdown example
This is an explanation
* item one
* item two
   * sub item one
   * sub item two
$$ c^2 = a^2 + b^2 $$

`DIVAnd` is the package name.     
It was developed at the [GHER](https://github.com/gher-ulg)

#### Juno

* Based on the Atom editor from GitHub
* Integrates an editor, command line and documentation browser
* Available from http://junolab.org/

![atom](Images/julia-atom.png)

# Julia documentation

* The manual: https://docs.julialang.org
* Tutorials and books: https://julialang.org/learning/


## Comparision with other languages


[Noteworthy Differences from other Languages](https://docs.julialang.org/en/stable/manual/noteworthy-differences/).

### Differences from MATLAB
* Julia arrays are indexed with square brackets: `A[i,j]`.
* Julia arrays are assigned by reference. After A=B, changing elements of B will modify A as well. If you need to copy an array, use `b = copy(a)`.
* Julia function parameters are passed and assigned by reference. If a function modifies an array, the changes will be visible in the caller.
* A bang (!) indicates if a function changes one of its argument
* In Julia, parentheses must be used to call a function with zero arguments, like in tic() and toc().
* Julia's single quotes enclose characters, not strings.
* Julia does not automatically grow arrays in an assignment statement. 
* Scope of variables in a loop is local: 

   for i = 1:10
        z = i
   end

  will result in undefined z after the loop unless defined before the loop 
* In MATLAB, ranges are sometimes enclosed with brackets, e.g. `[1:10]`. This is also valid Julia code, but it generates a vector whose single element is a range from 1 to 10. To declare a range in Julia, simply use `1:10` without the brackets.

### Difference from Python
* Julia requires `end` keyword to end a block (loop, condition, ...).
* In Julia, indexing of arrays, strings, etc. is 1-based not 0-based.
* Julia's slice indexing includes the last element, unlike in Python. `a[2:3]` in Julia is `a[1:3]` in Python.
* Julia does not support negative indexes. In particular, the last element of a list or array is indexed with `end` in Julia, not `-1` as in Python.

[MATLAB–Python–Julia cheatsheet](https://cheatsheets.quantecon.org/)

* Julia is compiled
   * For loop are fast, but
   * Loading modules is slower than in other languages
   * Sometimes Julia needs to be restarted (in IJulia the kernel needs to be restarted) when e.g. a module is changed.

# First steps in Julia

## Numbers

* Use a dot (.) as decimal separator (e.g. 3.14 and not 3,14)
* You can use the scientific notation $a \times 10^{-b}$ using the e-notation. (e.g. $3 \times10^{-7}$ becomes 3e-7) 
* Use Julia as a calculator:

In [1]:
3e-7

3.0e-7

In [2]:
4/2

2.0

In [3]:
1 + 3 * 4/2 

7.0

The usual operator precedence applies.

## Useful constants

Various constants are also pre-defined:     
π: pi (3.141592...)     
e: Euler's number (2.7182818...)     
im: the imaginary number (im² = -1)     
Inf (Infinity, result from e.g. 1/0) and     
NaN (Not a Number - result from e.g. 0/0).

**Examples:**

In [4]:
π 

π = 3.1415926535897...

*[Euler's identity](https://en.wikipedia.org/wiki/Euler%27s_identity)* (should be -1):

In [5]:
exp(-im * π)

-1.0 - 1.2246467991473532e-16im

## Variables

* Numbers (and any other data type) can be put into variables
* The value of a variable is referenced by its name
* A variable name can be composed by letters (a-z and A-Z, including greek letters, accents,...), numbers (0-9), underscore (_) and some unicode symbols (like greek letters). The first character cannot be a number.

**Example:**

In [6]:
temp = 21

21

This one is not valid (starts with a digits):

In [7]:
2temp = 1.

LoadError: syntax: "2" is not a valid function argument name

To see the content of the variable `temp`, use the [`@show`](https://docs.julialang.org/en/latest/base/base/#Base.@show) macro:

In [8]:
@show temp;

temp = 21


Any expression can now include the variable `temp`:

In [9]:
2 * temp

42

* The variable `temp` has now the value 21. The value of the variable can be changed later on.
* An assignment without a final semicolon echoes its value to the screen
* Careful: the value of constants can be overwritten. The following is allowed but not encouraged:
    	
```julia        
    pi = 3; # do not do this
```

The command [`varinfo()`](https://docs.julialang.org/en/stable/stdlib/InteractiveUtils/#InteractiveUtils.varinfo) lists the currently defined variables and the loaded modules, as well as their size in a markdown table.

In [12]:
varinfo()

| name |    size | summary |
|:---- | -------:|:------- |
| Base |         | Module  |
| Core |         | Module  |
| Main |         | Module  |
| temp | 8 bytes | Int64   |


The command [`typeof()`](https://docs.julialang.org/en/stable/base/base/#Core.typeof) returns the type of a variable:

In [14]:
typeof(temp)

Int64

## Strings
They are delimited by double quotes:

In [16]:
s = "Hello world"
print(s);

Hello world

How to use a double quote in a string?      
→ place a backslash `\` before it:

In [18]:
s = "The letter \"A\" is the first letter of the alphabet."
print(s)

The letter "A" is the first letter of the alphabet.

## Symbols

* A symbol is an [interned string](https://en.wikipedia.org/wiki/String_interning) identifier which means that every string symbol is replaced internally by a number
* This makes comparison between symbols faster than comparison between strings
* Symbols are also used in metaprogramming (julia code which produces julia code).

In [19]:
:mysymbol

:mysymbol

## Vectors and matrices
The module [`LinearAlgebra`](https://docs.julialang.org/en/stable/stdlib/LinearAlgebra/) provides useful linear algebra operations.

In [28]:
using LinearAlgebra

Vectors are list of numbers. The column vector $\left(\begin{array}{c}1 \\ 2 \\ 3 \end{array} \right)$ is represented by:

In [25]:
[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

Matrices are tables of numbers. Rows are separated by a semicolon. The matrix 
$\left(\begin{array}{cc}1 & 2 \\ 3 & 4 \end{array} \right)$ is represented by:

In [26]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

The [determinant](https://en.wikipedia.org/wiki/Determinant) can be for example computed with `det`:

In [29]:
LinearAlgebra.det([1 2; 3 4])

-2.0

There are no "row vectors", just matrices with one row:

In [30]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [31]:
[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

### Ranges

Consecutive elements can be written as:

    `first:step:last`
    
or simply, if the step is 1,
    	
    `first:last`
    
Use the function [`collect`](https://docs.julialang.org/en/stable/base/collections/#Base.collect-Tuple{Type,Any}) or `[first:step:last;]` to transform a range into a vector:
   
Instead of typing this:  

In [32]:
[1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

one could simply write this as:

In [33]:
1:5

1:5

which has the `UnitRange` type.

In [34]:
@show(typeof(1:5));

typeof(1:5) = UnitRange{Int64}


Or the full list:

In [35]:
collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [36]:
@show(typeof(collect(1:5)));

typeof(collect(1:5)) = Array{Int64,1}


Now if we need only every second element:

In [37]:
1:2:6

1:2:5

In [38]:
collect(1:2:6)

3-element Array{Int64,1}:
 1
 3
 5

Note that 6 is not part of the previous range.

## Indexing

Consider the following vector:

In [39]:
a = [2,5,7,19,2]

5-element Array{Int64,1}:
  2
  5
  7
 19
  2

* Individual elements of a vector or matrix can be addressed by their index using square brackets.
* The second element of a vector `a` is for example `a[2]`

In [40]:
a[2]

5

In [41]:
length(a)

5

In [42]:
a[length(a)]

2

The special word `end` refers to the last index.     
`end` is also useful to refer to elements with respect to the last one:

In [43]:
a[end]

2

In [44]:
a[end-2]

7

One can also use a list of indexes to extract a part of the vector

In [46]:
a[[2,3,4]]
# a[2,3,4] would mean we want to access the (single) index [2, 3, 4]

3-element Array{Int64,1}:
  5
  7
 19

Or simply:

In [47]:
a[2:4]

3-element Array{Int64,1}:
  5
  7
 19

The symbol colon **:** is a short-hand for 1:end

In [48]:
a[1:end]

5-element Array{Int64,1}:
  2
  5
  7
 19
  2

In [49]:
a[:]

5-element Array{Int64,1}:
  2
  5
  7
 19
  2

## Matrix indexing

* For matrices, two indices are generally used.
* The element at the second row and the first column of a matrix A is for example `A[2,1]`

In [53]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [54]:
A[2,1]

3

In [55]:
A[:,2]

2-element Array{Int64,1}:
 2
 4

In [56]:
A[3]

2

* If a matrix is indexed with only one subscript, the matrix is treated as a vector where all columns are concatenated.
* Julia supports also higher-dimensional arrays and indexing works similarily.

## Additional data structures

### Dictionaries

A dictionary [`Dict`](https://docs.julialang.org/en/stable/base/collections/#Base.Dict) is a data structure that maps keys to values.      
**Example:**

In [58]:
data = Dict("Temperature" => 20.23, "Salinity" => 37.54)

Dict{String,Float64} with 2 entries:
  "Temperature" => 20.23
  "Salinity"    => 37.54

Dictionaries are useful to retrieve an entry using the key:

In [59]:
data["Temperature"]

20.23

### Tuple

* A tuple is a (usually short) sequence of values (those values can be of any type)
* A tuple cannot be modified (e.g. you cannot add another element to a tuple or replace an existing element)
* Tuples are less flexible, but more efficient than vectors
* A tuple is enclosed with a round parentesis, e.g. `(12,45,"a string")` or `(42,)` (here the last comma is necessary to distinguish between a parentesis enclosing a tuple and parentesis grouping an expression)

In [60]:
liegeCoordinates = (50.633333, 5.566667)
@show typeof(liegeCoordinates);

typeof(liegeCoordinates) = Tuple{Float64,Float64}


In [61]:
# We cannot change the values: tuples are immutable!
liegeCoordinates[1] =  50.7

LoadError: MethodError: no method matching setindex!(::Tuple{Float64,Float64}, ::Float64, ::Int64)

Tuples are typically used for output arguments (and sometimes for input arguments too)     
We'll come back to functions later in this notebook:

In [63]:
function myfunction(a,b,the_rest...)
    return (a+1,b+2,sum(the_rest))
end

p1,p2,p3 = myfunction(1,2,3,4)

@show p1
@show p2
@show p3

p1 = 2
p2 = 4
p3 = 7


7

In [64]:
all_p =  myfunction(1,2,3,4)

@show all_p;
@show typeof(all_p);

all_p = (2, 4, 7)
typeof(all_p) = Tuple{Int64,Int64,Int64}


# Operators

* Scalar and matrix operations: **+** sum, **-** difference, __*__ multiplication, **/** division
* Element-wise matrix operations: __.*__ multiply element-wise, __./__ divide element-wise 

## Comparison operators

equal (`==`) and different (`!=`) 

In [65]:
2 == 1

false

In [70]:
9 == 3*3

true

The triple equal is used to ensure the type of the 2 arguments is the same:

In [71]:
@show 2 == 2.;
@show 2 === 2.;  # integer vs. float

2 == 2.0 = true
2 === 2.0 = false


The dot is used for element-wise comparisons:

In [72]:
[1 2 3] == [1 3 2]

false

In [73]:
[1 2 3] .== [1 3 2]

1×3 BitArray{2}:
 true  false  false

Be aware of the limited precision of floating point numbers

In [74]:
2.0000000000000001 == 2

true

Element-wise equal (`.==`), element-wise different (`.!=`)

In [75]:
[1 2 3] .== [1 3 2]

1×3 BitArray{2}:
 true  false  false

In [76]:
[1 2 3] .!= [3 2 1]

1×3 BitArray{2}:
 true  false  true

Comparision between numbers: <, >, <= (≤), => (≥)

In [77]:
30 > 25

true

Element-wise comparision between vector and matrices: .<, .>, .<= (.≤), .=> (.≥)

In [78]:
[1,2,3] .> 2

3-element BitArray{1}:
 false
 false
  true

In [79]:
[1,2,3] .> [3,1,2]

3-element BitArray{1}:
 false
  true
  true

Logical "and" (&&) logical "or" (||) (with short-circuit evaluation)

In [82]:
temperature = 30;
precipitation = 10;

if temperature > 25 && precipitation == 0
    print("go outside!")
else
    print("stay in and code")
end

stay in and code

* logical element-wise "and" (.&) logical element-wise "or" (.|)

* The results of such operators can also be used to index an array
    
* For example return all elements in the variable T which are greater than 10 but less than 20.
    

In [83]:
T = [27,17,20,26,32]
T[20 .< T .& T .< 30]

2-element Array{Int64,1}:
 27
 26

In [84]:
T .< 30

5-element BitArray{1}:
  true
  true
  true
  true
 false

* The function [`findall(condition)`](https://docs.julialang.org/en/stable/base/arrays/#Base.findall-Tuple{Any}) returns the indexes of all elements where the condition is true.

In [87]:
findall(20 .< T .& T .< 30)

2-element Array{Int64,1}:
 1
 4

False is zero and true is 1. For instance to count the number of elements in the vector T which are larger than 20 one can use sum(T .> 20).

In [88]:
sum([1,2,3])

6

In [89]:
sum([1,0,1])

2

In [90]:
sum(T .> 20)

3

# Useful functions

* sin, cos, tan: trigonometric functions
* asin, acos, atan: inverse trigonometric functions
* log, log2, log10: natural, base 2 and base 10 logarithms: 
* exp: exponentiation
* abs: absolute value
* sqrt: square root
* mean: mean
* median: median
* std: standard deviation
* var: variance
* mod: modulo (useful to manipulate e.g. the longitude)
* isnan: Check if variable is NaN. Note that NaN == NaN is false!
* inv: inverse of a matrix
* sum: sum of all elements
* prod: product of all elements
* maximum,minimum: maximum,minimum value in an array
* max,min: maximum,minimum value of all arguments
* isnan: true if a value is NaN
* isinf: true if a value is Inf

These function can also operate of a given dimension: sum(array,dimension)

Find out more of these function by typing ? followed by the function name. 

In [92]:
?open

search: open isopen propertynames module_parent CompositeException operm



```
open(filename::AbstractString; keywords...) -> IOStream
```

Open a file in a mode specified by five boolean keyword arguments:

| Keyword    | Description            | Default                               |
|:---------- |:---------------------- |:------------------------------------- |
| `read`     | open for reading       | `!write`                              |
| `write`    | open for writing       | `truncate \| append`                  |
| `create`   | create if non-existent | `!read & write \| truncate \| append` |
| `truncate` | truncate to zero size  | `!read & write`                       |
| `append`   | seek to end            | `false`                               |

The default when no keywords are passed is to open files for reading only. Returns a stream for accessing the opened file.

---

```
open(filename::AbstractString, [mode::AbstractString]) -> IOStream
```

Alternate syntax for open, where a string-based mode specifier is used instead of the five booleans. The values of `mode` correspond to those from `fopen(3)` or Perl `open`, and are equivalent to setting the following boolean groups:

| Mode | Description                   | Keywords                       |
|:---- |:----------------------------- |:------------------------------ |
| `r`  | read                          | none                           |
| `w`  | write, create, truncate       | `write = true`                 |
| `a`  | write, create, append         | `append = true`                |
| `r+` | read, write                   | `read = true, write = true`    |
| `w+` | read, write, create, truncate | `truncate = true, read = true` |
| `a+` | read, write, create, append   | `append = true, read = true`   |

# Examples

```jldoctest
julia> io = open("myfile.txt", "w");

julia> write(io, "Hello world!");

julia> close(io);

julia> io = open("myfile.txt", "r");

julia> read(io, String)
"Hello world!"

julia> write(io, "This file is read only")
ERROR: ArgumentError: write failed, IOStream is not writeable
[...]

julia> close(io)

julia> io = open("myfile.txt", "a");

julia> write(io, "This stream is not read only")
28

julia> close(io)

julia> rm("myfile.txt")
```

---

```
open(f::Function, args...; kwargs....)
```

Apply the function `f` to the result of `open(args...; kwargs...)` and close the resulting file descriptor upon completion.

# Examples

```jldoctest
julia> open("myfile.txt", "w") do io
           write(io, "Hello world!")
       end;

julia> open(f->read(f, String), "myfile.txt")
"Hello world!"

julia> rm("myfile.txt")
```

---

```
open(command, stdio=devnull; write::Bool = false, read::Bool = !write)
```

Start running `command` asynchronously, and return a tuple `(stream,process)`.  If `read` is true, then `stream` reads from the process's standard output and `stdio` optionally specifies the process's standard input stream.  If `write` is true, then `stream` writes to the process's standard input and `stdio` optionally specifies the process's standard output stream.

---

```
open(f::Function, command, mode::AbstractString="r", stdio=devnull)
```

Similar to `open(command, mode, stdio)`, but calls `f(stream)` on the resulting process stream, then closes the input stream and waits for the process to complete. Returns the value returned by `f`.


In [93]:
apropos("mean")

Base.@nospecialize
Base.:∘
Base.IteratorEltype
Base.isconcretetype
Base.RangeStepStyle
Base.Slice
Base.isbitsunion
Base.@pure
Base.nextind
Base.isdispatchtuple
Base.prevind
Base.isequal
Base.Condition
Base.reduce
Base.IteratorSize
Base.isbitstype
Base.IRShow.compute_ir_line_annotations
Base.Broadcast.newindex
Base.Sys.isbsd
Base.Threads.atomic_cas!
Base.CoreLogging.@info
Base.CoreLogging.@debug
Base.CoreLogging.@warn
Base.CoreLogging.@error
Base.CoreLogging.@logmsg
Base.Math.rem_pio2_kernel
Base.Sort.partialsortperm
Base.sortperm
Base.Multimedia.display
LibGit2.isbare
LibGit2.BlameOptions
LibGit2.DiffOptionsStruct
LibGit2.clone
LibGit2.treewalk
Profile.fetch
Random.randn!
Base.randn
Base.sqrt
LinearAlgebra.LAPACK.gesvx!
SparseArrays.sprand
Test.test_expr!
Test.@testset
Statistics.var
Statistics.middle
Statistics.mean
Statistics.stdm
Statistics.median
Statistics.mean!
Statistics.varm
Statistics.std
IJulia.set_cur_msg


In [94]:
?mean

search: SegmentationFault macroexpand @macroexpand @macroexpand1 module_parent



Add `using Statistics` to your imports.
  likely near /home/ctroupin/.julia/packages/IJulia/9RcVi/src/kernel.jl:32
Add `using Statistics` to your imports.
  likely near /home/ctroupin/.julia/packages/IJulia/9RcVi/src/kernel.jl:32


```
mean(itr)
```

Compute the mean of all elements in a collection.

!!! note
    If `itr` contains `NaN` or [`missing`](@ref) values, the result is also `NaN` or `missing` (`missing` takes precedence if array contains both). Use the [`skipmissing`](@ref) function to omit `missing` entries and compute the mean of non-missing values.


# Examples

```jldoctest
julia> mean(1:20)
10.5

julia> mean([1, missing, 3])
missing

julia> mean(skipmissing([1, missing, 3]))
2.0
```

---

```
mean(f::Function, itr)
```

Apply the function `f` to each element of collection `itr` and take the mean.

```jldoctest
julia> mean(√, [1, 2, 3])
1.3820881233139908

julia> mean([√1, √2, √3])
1.3820881233139908
```

---

```
mean(A::AbstractArray; dims)
```

Compute the mean of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> mean(A, dims=1)
1×2 Array{Float64,2}:
 2.0  3.0

julia> mean(A, dims=2)
2×1 Array{Float64,2}:
 1.5
 3.5
```


# The file system

* On every current operating system, files are organized in a tree of directories starting from a root directory
* The absolute path of a directory or file defines which directories to follow starting from the root directory to the given directory or file
* In Linux/UNIX/Max OS X, files and directory names are separated by a slash (/), on Windows by a backslash (\\)
* In order to avoid to deal with long path names, every program has a current working directory
* The current working directory from Julia can be queried with the command `pwd()`.
* The relative path of a directory or file defines which directories to follow starting from the current directory to the given directory or file
* In relative path, two dots (`..`) represent the parent directory.
* To change the current directory, you can use the command `cd`. For Linux and Mac OS X:

```julia
cd("/home/MyDir")
``` 

Under Windows you need to you the following:

```julia
cd("C:\\Users\\MyDir")
```

Note that here two backslashes are necessary ([why?](https://stackoverflow.com/questions/28328052/why-do-i-have-to-use-double-backslashes-for-file-paths-in-code)).

# Importing/Exporting data

In [96]:
using DelimitedFiles

## ASCII format

To read ASCII data in Julia, tables should be saved as an ASCII text file using space or a special characters as separator. Each line corresponds to one row. Make sure that a dot is used as a decimal separator.

In [103]:
# Need to provide the file?
data = readdlm("./data/sealevel.txt",comment_char='%')

Add `using DelimitedFiles` to your imports.
  likely near In[103]:2
Add `using DelimitedFiles` to your imports.
  likely near In[103]:2


745×8 Array{Any,2}:
     "%year"   "month"    "day"    "hour"   "minute"  …   "flag1"   "flag2"
 2004         1          1        0        0             0.003     0       
 2004         1          1        1        0             0.002     0       
 2004         1          1        2        0             0.006     0       
 2004         1          1        3        0             0.003     0       
 2004         1          1        4        0          …  0.004     0       
 2004         1          1        5        0             0.003     0       
 2004         1          1        6        0             0.002     0       
 2004         1          1        7        0             0.003     0       
 2004         1          1        8        0             0.002     0       
 2004         1          1        9        0          …  0.002     0       
 2004         1          1       10        0             0.002     0       
 2004         1          1       11        0             0.002     0

Saving the variable data in the file `data.txt` using the ASCII format

In [104]:
writedlm("./data/data.txt", data)

## NetCDF format
The reading/write of netCDF files is done using the [`NCDatasets`](https://github.com/Alexander-Barth/NCDatasets.jl) module, which is automatically installed with `DIVAnd`.
You can also find more information in the notebook [07-reading-data](07-reading-data.ipynb).

* Reading a variable called `var`  from a netCDF file

```julia
using NCDatasets
ds = Dataset("file.nc")
data = ds["var"][:];
close(ds)
```

* Writing a variable called `var` data to a netCDF file

```julia
ds = Dataset("file.nc","c")

# Define the dimension "lon" and "lat" with the size 100 and 110 resp.
defDim(ds,"lon",100)
defDim(ds,"lat",110)


# Define the variables temperature and salinity
v = defVar(ds,"temperature",Float32,("lon","lat"))
# write a the complete data set
v[:,:] = data
close(ds)
```

# Scripts

A script is a series of commands that can be collected in a script file.    
A script file has the extension `.jl`.

How can Julia find your script file?     
* it must be either in your current work directory
* the directory containing the script file must be added to the search path using `LOAD_PATH`. For example

```julia
push!(LOAD_PATH,"/some/path")
```

The code in a script is executed when using [`include`](https://docs.julialang.org/en/stable/base/base/#Base.include), which evaluates the contents of the input source file:

```
include("filename.jl")
```

# Functions

Functions are similar to scripts.     
Unlike scripts, functions can have input/output parameters.    
For example a function calculating the speed of ocean current based on the zonal and meridional component

In [105]:
function current_speed(u,v)
   speed = sqrt(u^2 + v^2)
   return speed
end

current_speed (generic function with 1 method)

In [106]:
speed2 = current_speed(5,5)

7.0710678118654755

Another example of function: we compute naively the number of days without rain:

In [107]:
function dayswithoutrain(P)
    #....
    days = 0
    for i = 1 : length(P)
        # do something with i
        if P[i] == 0
            # count
            days = days+1
        end
        @show days
    end    
    return days
    
    # Note: what comes after the `return` is not exectuted
    print("The function has already finished")
end

dayswithoutrain (generic function with 1 method)

In [108]:
P = [0,0,0,3,4,5,3,0,0]
days = dayswithoutrain(P)    

days = 1
days = 2
days = 3
days = 3
days = 3
days = 3
days = 3
days = 4
days = 5


5

# Modules

Functions can be grouped into a module. 


## Update module list

Before installing a module is it recommended to update the module list to ensure that the latest version of a module will be installed.

```julia
Pkg.update()
```

## Installation of modules

From Julia-0.7.0 on, the installation of packages has changed, as there is now a Pkg REPL-mode entered from the Julia REPL using the key `]` (https://docs.julialang.org/en/stable/stdlib/Pkg/#Getting-Started-1).     
The commands `Pkg.add()` and `Pkg.clone()`, is deprecated but still works, for example:

In [114]:
Pkg.add("PyPlot")

 Resolving package versions...


  likely near In[114]:1


  Updating `~/.julia/environments/v0.7/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]


Module can also be installed directly from a repository:

```julia
Pkg.clone("https://github.com/gher-ulg/DIVAnd.jl")
```

A module can be upgraded with:

In [115]:
Pkg.update("PyPlot")

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`


  likely near In[115]:1


 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]


A no-longer used module can be removed with `Pkg.rm("ModuleName")`.     
The list of available packages is obtained as follows:

In [121]:
Pkg.status()

    Status `~/.julia/environments/v0.7/Project.toml`
  [efc8151c] DIVAnd v2.0.1+ #Alex-0.7 (https://github.com/gher-ulg/DIVAnd.jl.git)
  [7073ff75] IJulia v1.9.2
  [85f8d34a] NCDatasets v0.3.1
  [d330b81b] PyPlot v2.6.0


  likely near In[121]:1


## Using modules

To access a function (e.g. the function `plot`) inside a module (e.g. `PyPlot`), one needs to load the module with `using`. The following loads the module `PyPlot`:

```julia
using PyPlot
```

Now the function `plot` can be called.
Alternatively, one can also use `import`:

```julia
import PyPlot
```
The function plot can be called as `PyPlot.plot`. The import statement is useful to indicate in the source code the origin of the different functions (and avoid possible naming conflicts).

A short summary of a module is generally available by issuing

```julia
?ModuleName
```

In [122]:
using PyPlot

┌ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
└ @ Base loading.jl:1187
┌ Warning: Deprecated syntax `call to `&` inside call to bitshift operator` at /home/ctroupin/.julia/packages/Colors/RvyvG/src/conversions.jl:170.
│ Use `parenthesized call to `&`` instead.
└ @ ~/.julia/packages/Colors/RvyvG/src/conversions.jl:170
┌ Warning: Deprecated syntax `call to `&` inside call to bitshift operator` at /home/ctroupin/.julia/packages/Colors/RvyvG/src/conversions.jl:170.
│ Use `parenthesized call to `&`` instead.
└ @ ~/.julia/packages/Colors/RvyvG/src/conversions.jl:170
┌ Warning: Deprecated syntax `call to `&` inside call to bitshift operator` at /home/ctroupin/.julia/packages/Colors/RvyvG/src/conversions.jl:171.
│ Use `parenthesized call to `&`` instead.
└ @ ~/.julia/packages/Colors/RvyvG/src/conversions.jl:171
┌ Info: Installing matplotlib via Anaconda's /home/ctroupin/miniconda3/bin/conda...
└ @ PyCall /home/ctroupin/.julia/packages/PyCall/fiJ3o/src/PyCall.jl:648


Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/ctroupin/miniconda3:

The following NEW packages will be INSTALLED:

    cycler:           0.10.0-py36_0        
    dbus:             1.13.2-h714fa37_1    
    expat:            2.2.5-he0dffb1_0     
    fontconfig:       2.13.0-h9420a91_0    
    freetype:         2.9.1-h8a8886c_0     
    glib:             2.56.1-h000015b_0    
    gst-plugins-base: 1.14.0-hbbd80ab_1    
    gstreamer:        1.14.0-hb453b48_1    
    icu:              58.2-h9c2bf20_1      
    jpeg:             9b-h024ee3a_2        
    kiwisolver:       1.0.1-py36hf484d3e_0 
    libpng:           1.6.34-hb9fc6fc_0    
    libuuid:          1.0.3-h1bed415_2     
    libxcb:           1.13-h1bed415_1      
    libxml2:          2.9.8-hf84eae3_0     
    matplotlib:       2.2.2-py36hb69df0a_2 
    pcre:             8.42-h439df22_0      
    pyparsing:        2.2.0-py36_1         
    pyqt:      

Excessive output truncated after 528444 bytes.

Note: had to run 
```
juliaPkg.add("VersionParsing")
```
in order to be able to use PyPlot.

In [ ]:
?PyPlot

# Dates
The [`Dates`](https://docs.julialang.org/en/stable/stdlib/Dates/#Dates-1) module provides several functions to deal with date and time.

In [124]:
using Dates

Julia has a structure called `DateTime` to represent a date and time.

In [128]:
lastsecond = Dates.DateTime(1999,12,31,23,59,59)

1999-12-31T23:59:59

The difference between two `DateTime`s returns a structure representing the number of milliseconds.

In [129]:
Dates.DateTime(2001,1,1)

2001-01-01T00:00:00

In [130]:
dt = Dates.DateTime(2001,1,1) - Dates.DateTime(2000,1,1)

31622400000 milliseconds

In [131]:
@show typeof(dt)

typeof(dt) = Millisecond


Millisecond

The time difference can be converted into days:

In [133]:
Dates.Day(Dates.DateTime(2001,1,1) - Dates.DateTime(2000,1,1))

366 days

Add a duration to a date

In [134]:
Dates.DateTime(2000,1,1) + Dates.Day(366)

2001-01-01T00:00:00

Compute number of days before or after `now()`:

In [137]:
Dates.value(Dates.DateTime(2018,9,7) - Dates.now()) / 1000 / 60 / 60 / 24

27.39884741898148

In [138]:
Dates.value(Dates.DateTime(2017,9,7) - Dates.now()) /(24*60*60*1000)

-337.6012162847222

**Exercice:**     
Compute in how many days is your next birthday using the previous functions.

# Control Flow
## Loops
Let your computer do repetitive tasks!      
Loops have a counter which takes successively all elements of a row vector

In [140]:
for i = [1 2 10 20]
    @show i
end

i = 1
i = 2
i = 10
i = 20


Loops are often used with a range of values

In [141]:
for i = 1:5
    @show i
end

i = 1
i = 2
i = 3
i = 4
i = 5


Explicit loops can sometimes be avoided,     
for example, sum all integer from 1 to 10

In [145]:
total = 0;
for i = 1:10
   total = total + i;
end
total

┌ Warning: Deprecated syntax `implicit assignment to global variable `total``.
│ Use `global total` instead.
└ @ nothing none:0


55

Can simply be computed as `sum(1:10)`.

# if-statement

* Sometimes your code needs to behave differently depending on some conditions.

* if-statement has the following structure.

```julia
if some_conditions
  # do something
else
  # do something else
end
```
The else section can be omitted.

For example.

```julia
if x < 0
   x = -x;
end
```

__Quiz:__ Which Julia function implements the last code example?

In [151]:
if Dates.dayname(Dates.dayofweek(Dates.today())) == "Friday"
   print("Have a nice weekend") 
end

Have a nice weekend