# Introduction to Julia

[`Julia`](https://julialang.org/) is a high-level programming language for technical computing which allows you to manipulate and analyse large data sets.
* The manual: https://docs.julialang.org
* Tutorials and books: https://julialang.org/learning/


## Why Julia?
 * Julia is build from the ground for technical computing. 
 * The language is close to the mathematical notation, for example to define a function $f(x) = 2x + 3$ in Julia is (among other possibilities):

```julia
f(x) = 2x + 3
```
  
 * It is free and open-source software.
 * The code is compiled to machine code and loops can be as fast as in other compiled languages (like Fortran or C).


## Instructions for installing Julia

1. Go to http://julialang.org/downloads/ and follow the instructions.
2. Install one editor with support for Julia, such as 
- [Visual Studio Code](https://code.visualstudio.com/),  
- notepad++, 
- emacs... 
- or even vim.

### Notes
- The `Juno` editor, previously suggested in this notebook, will not be updated anymore, since development focus has shifted to the Julia extension for `VSCode`.
- Recent versions of the installation procudure recommend to use [`Juliaup`](https://github.com/JuliaLang/juliaup), which is a Rust-based Julia version manager.

## Ways to run Julia

### Command line

Start a Julia session by typing `Julia` in a terminal. You will get the following screen (with another Julia version):
![cmd](Images/julia-commandline.png)

Tips:
* Use the `Tab` key to complete file, variable and function names
* `Up` and `down arrows` key to repeat a previously entered command
* `Control-R` to search a command
* On Windows enable "[quick edit](https://www.tekrevue.com/tip/boost-productivity-quickedit-mode-windows-command-prompt/)" for easier copy and pasting

### Jupyter notebook (web-browser)

* Web-interface for Julia (among others)
* The Julia package `IJulia` which also installs [Jupyter](http://jupyter.org/)
* Various [keyboard shortcuts](https://www.cheatography.com/weidadeyue/cheat-sheets/jupyter-notebook/) are defined to be productive with jupyter notebooks
* General documentation of [Jupyter Notebooks](http://jupyter-notebook.readthedocs.io)

![cmd](Images/julia-jupyter.png)

### VSCode

* Integrates an editor, command line and documentation browser
* The VSCode extension for Julia is available from https://www.julia-vscode.org/, and can also be installed directly using the "Extensions" menu.
* VSCode also allows users to visualise [Jupyter notebooks](https://code.visualstudio.com/docs/datascience/jupyter-notebooks) directly.

## Comparison with other languages

* [Julia compared to other languages](https://docs.julialang.org/en/v1/#man-julia-compared-other-languages)
* [Noteworthy Differences from other Languages](https://docs.julialang.org/en/v1/manual/noteworthy-differences/).

Julia is mostly influenced by MATLAB, but there are some significant differences.

### Differences from MATLAB

* Julia arrays are indexed with square brackets: `A[i,j]`.
* Julia arrays are assigned by reference. After `A=B`, changing elements of `B` will modify `A` as well. If you need to copy an array, use `b = copy(a)`.
* Julia function parameters are passed and assigned by reference. If a function modifies an array, the changes will be visible in the caller.
* A bang (!) indicates if a function that changes one of its argument
* In Julia, parentheses must be used to call a function with zero arguments, like in `tic()` and `toc()`.
* Julia's single quotes enclose characters, not strings.
* Julia does not automatically grow arrays in an assignment statement. 
* Scope of variables in a loop is local: 

```julia
   for i = 1:10
        z = i
   end
```

  will result in undefined z after the loop unless defined before the loop 
* In MATLAB, ranges are sometimes enclosed with brackets, e.g. `[1:10]`. This is also valid Julia code, but it generates a vector whose single element is a range from 1 to 10. To declare a range in Julia, simply use `1:10` without the brackets.

### Differences from Python
* Julia requires `end` keyword to end a block (loop, condition, ...).
* In Julia, indexing of arrays, strings, etc. is 1-based, not 0-based.
* Julia's slice indexing includes the last element, unlike in Python. `a[2:3]` in Julia is `a[1:3]` in Python.
* Julia does not support negative indexes. In particular, the last element of a list or array is indexed with `end` in Julia, not `-1` as in Python.

[MATLAB–Python–Julia cheatsheet](https://cheatsheets.quantecon.org/)

* Julia is compiled
   * For loop are fast, but
   * Loading modules is slower than in other languages
   * Sometimes Julia needs to be restarted (in IJulia the kernel needs to be restarted) when e.g. a module is changed.

# First steps in Julia
## Displaying on screen
There are many ways to display the content of a variable on the screen. 
The main difference between `print` and `println` is that the latter add a newline after the text.

In [1]:
mytext = "Hello!"
mynum = 2256
print(mytext)
print(mynum)
println(mytext)
println(mynum)

Hello!2256Hello!
2256


The macro `@show` prints one or more expressions as well as their results:

In [2]:
@show(mytext);

mytext = "Hello!"


In a code it is good practice to use log messages (instead of simple `print`). Julia defines different levels of message (you will see that the last message doesn't produce any output):

In [3]:
@info("Let's learn Julia")
@warn("This variable has not been defined")
@error("This is an error")
@debug("Only visible for debugging")

[ Info: Let's learn Julia
┌ Warning: This variable has not been defined
└ @ Main In[3]:2
┌ Error: This is an error
└ @ Main In[3]:3


## Numbers

* Use a dot (.) as decimal separator (e.g. 3.14 and not 3,14)
* You can use the scientific notation $a \times 10^{-b}$ using the e-notation. (e.g. $3 \times10^{-7}$ becomes 3e-7) 
* Underscores can be used to improve readability of large numbers
* Use Julia as a calculator:

In [4]:
3e-7

3.0e-7

In [5]:
4/2

2.0

In [6]:
2_000_000 == 2000000

true

In [7]:
1 + 3 * 4/2 

7.0

The usual operator precedence applies.

## Useful constants

Various constants are also pre-defined:     
π: pi (3.141592...)     
e: Euler's number (2.7182818...)     
im: the imaginary number (im² = -1)     
Inf (Infinity, result from e.g. 1/0) and     
NaN (Not a Number - result from e.g. 0/0).

**Examples:**

In [8]:
π 

π = 3.1415926535897...

[*Euler's identity*](https://en.wikipedia.org/wiki/Euler%27s_identity) (should be -1):

In [9]:
exp(-im * π)

-1.0 - 1.2246467991473532e-16im

## Variables

* Numbers (and any other data type) can be put into variables
* The value of a variable is referenced by its name
* A variable name can be composed by letters (a-z and A-Z, including greek letters, accents,...), numbers (0-9), underscore (_) and some unicode symbols (like greek letters). The first character cannot be a number.

**Example:**

In [10]:
temp = 21

21

This one is not valid (starts with a digits):
```julia
2temp = 1.
```

Produces the error:
```
syntax: "2" is not a valid function argument name
```



To see the content of the variable `temp`, use the [`@show`](https://docs.julialang.org/en/latest/base/base/#Base.@show) macro:

In [11]:
@show temp;

temp = 21


Any expression can now include the variable `temp`:

In [12]:
2 * temp

42

The value can be used in a string using `$( )`:

In [13]:
"The temperature is $(temp)°C"

"The temperature is 21°C"

* The variable `temp` has now the value 21. The value of the variable can be changed later on.
* An assignment without a final semicolon echoes its value to the screen
* Careful: the value of constants can be overwritten. The following is allowed but not encouraged:
    	
```julia        
    pi = 3; # do not do this
```
* However, if you explicitely define a variable as a constant, trying to modify it will result in a warning.

In [14]:
const kb = 1.38064852e-23
kb = 1.38e-23

1.38e-23

The command [`varinfo()`](https://docs.julialang.org/en/stable/stdlib/InteractiveUtils/#InteractiveUtils.varinfo) lists the currently defined variables and the loaded modules, as well as their size in a markdown table.

In [15]:
varinfo()

| name   |     size | summary           |
|:------ | --------:|:----------------- |
| Base   |          | Module            |
| Core   |          | Module            |
| Main   |          | Module            |
| kb     |  8 bytes | Float64           |
| mynum  |  8 bytes | Int64             |
| mytext | 14 bytes | 6-codeunit String |
| temp   |  8 bytes | Int64             |


The command [`typeof()`](https://docs.julialang.org/en/stable/base/base/#Core.typeof) returns the type of a variable:

In [16]:
typeof(temp)

Int64

## Strings
They are delimited by double quotes (while characters are delimited by simple quotes):

In [17]:
s = "Hello world"
println(s);
char = 'ù'
println(typeof(char))

Hello world
Char


How to use a double quote in a string?      
→ place a backslash `\` before it:

In [18]:
s = "The letter \"A\" is the first letter of the alphabet."
print(s)

The letter "A" is the first letter of the alphabet.

## Symbols

* A symbol is an [interned string](https://en.wikipedia.org/wiki/String_interning) identifier which means that every string symbol is replaced internally by a number
* This makes comparison between symbols faster than comparison between strings
* Symbols are also used in metaprogramming (Julia code which produces Julia code).

In [19]:
:mysymbol

:mysymbol

In [20]:
typeof(:mysymbol)

Symbol

## Vectors and matrices
The module [`LinearAlgebra`](https://docs.julialang.org/en/stable/stdlib/LinearAlgebra/) provides useful linear algebra operations.

In [21]:
using LinearAlgebra

Vectors are list of numbers. The column vector $\left(\begin{array}{c}1 \\ 2 \\ 3 \end{array} \right)$ is represented by:

In [22]:
[1,2,3]

3-element Vector{Int64}:
 1
 2
 3

Matrices are tables of numbers. Rows are separated by a semicolon. The matrix 
$\left(\begin{array}{cc}1 & 2 \\ 3 & 4 \end{array} \right)$ is represented by:

In [23]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

### Ranges

Consecutive elements can be written as:

    `first:step:last`
    
or simply, if the step is 1,
    	
    `first:last`
    
Use the function [`collect`](https://docs.julialang.org/en/stable/base/collections/#Base.collect-Tuple{Type,Any}) or `[first:step:last;]` to transform a range into a vector:
   
Instead of typing this:  

In [24]:
[1,2,3,4,5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

one could simply write this as:

In [25]:
1:5

1:5

and convert if to a vector (if needed) with `collect( )`.

Now if we need only every second element:

In [26]:
1:2:6

1:2:5

Note that 6 is not part of the previous range.

## Indexing

Consider the following vector:

In [27]:
a = [2,5,7,19,2]

5-element Vector{Int64}:
  2
  5
  7
 19
  2

* Individual elements of a vector or matrix can be addressed by their index using square brackets.
* The second element of a vector `a` is for example `a[2]`

The special word `end` refers to the last index.     
`end` is also useful to refer to elements with respect to the last one:

In [28]:
a[end]

2

In [29]:
a[end-2]

7

One can also use a list of indexes to extract a part of the vector

In [30]:
a[[2,3,4]]
# a[2,3,4] would mean we want to access the (single) index [2, 3, 4]

3-element Vector{Int64}:
  5
  7
 19

Or simply:

In [31]:
a[2:4]

3-element Vector{Int64}:
  5
  7
 19

The symbol colon **:** is a short-hand for 1:end

## Matrix indexing

* For matrices, two indices are generally used.
* The element at the second row and the first column of a matrix A is for example `A[2,1]`

In [32]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [33]:
A[2,1]

3

In [34]:
A[:,2]

2-element Vector{Int64}:
 2
 4

Julia supports also higher-dimensional arrays and indexing works similarily.

## Additional data structures

### Dictionaries

A dictionary [`Dict`](https://docs.julialang.org/en/v1/base/collections/index.html#Dictionaries-1) is a data structure that maps keys to values.      
**Example:**

In [35]:
data = Dict("Temperature" => 20.23, "Salinity" => 37.54)

Dict{String, Float64} with 2 entries:
  "Temperature" => 20.23
  "Salinity"    => 37.54

Dictionaries are useful to retrieve an entry using the key:

In [36]:
data["Temperature"]

20.23

### Tuple

* A tuple is a (usually short) sequence of values (those values can be of any type)
* A tuple cannot be modified (e.g. you cannot add another element to a tuple or replace an existing element)
* Tuples are less flexible, but more efficient than vectors
* A tuple is enclosed with a round parentesis, e.g. `(12,45,"a string")` or `(42,)` (here the last comma is necessary to distinguish between a parentesis enclosing a tuple and parentesis grouping an expression)

In [37]:
liegeCoordinates = (50.633333, 5.566667)
@show typeof(liegeCoordinates);

typeof(liegeCoordinates) = Tuple{Float64, Float64}


We cannot change the values: tuples are immutable!
you will see the error

```julia
liegeCoordinates[1] =  50.7

MethodError: no method matching setindex!(::Tuple{Float64,Float64}, ::Float64, ::Int64)
```

Tuples are typically used for output arguments (and sometimes for input arguments too)     
We'll come back to functions later in this notebook.

# Operators

* Scalar and matrix operations: **+** sum, **-** difference, __*__ multiplication, **/** division
* Element-wise matrix operations: __.*__ multiply element-wise, __./__ divide element-wise 

## Comparison operators

equal (`==`) and different (`!=`) 

In [38]:
2 == 1

false

In [39]:
9 == 3*3

true

The dot is used for element-wise comparisons:

In [40]:
[1 2 3] == [1 3 2]

false

In [41]:
[1 2 3] .== [1 3 2]

1×3 BitMatrix:
 1  0  0

Be aware of the limited precision of floating point numbers

In [42]:
2.0000000000000001 == 2

true

Element-wise different (`.!=`)

In [43]:
[1 2 3] .!= [3 2 1]

1×3 BitMatrix:
 1  0  1

Comparision between numbers: <, >, <= (≤), => (≥)

In [44]:
30 > 25

true

Element-wise comparision between vector and matrices: .<, .>, .<= (.≤), .=> (.≥)

In [45]:
[1,2,3] .> 2 

3-element BitVector:
 0
 0
 1

In [46]:
[1,2,3] .> [3,1,2]

3-element BitVector:
 0
 1
 1

Logical "and" (`&&`) logical "or" (`||`) (with short-circuit evaluation)

In [47]:
temperature = 30;
precipitation = 10;

if temperature > 25 && precipitation == 0
    print("go outside!")
else
    print("stay in and code")
end

stay in and code

* logical element-wise "and" (.&) logical element-wise "or" (.|)

* The results of such operators can also be used to index an array
    
* For example return all elements in the variable T which are greater than 10 but less than 20.
    

In [48]:
T = [27,17,20,26,32]
T[20 .< T .& T .< 30]

2-element Vector{Int64}:
 27
 26

In [49]:
T .< 30

5-element BitVector:
 1
 1
 1
 1
 0

This list of 1's and 0's can be turned into a list of indices using `findall`:

In [50]:
findall(T .< 30)

4-element Vector{Int64}:
 1
 2
 3
 4

# Useful functions

* sin, cos, tan: trigonometric functions
* asin, acos, atan: inverse trigonometric functions
* log, log2, log10: natural, base 2 and base 10 logarithms: 
* exp: exponentiation
* abs: absolute value
* sqrt: square root
* mean: mean
* median: median
* std: standard deviation
* var: variance
* mod: modulo (useful to manipulate e.g. the longitude)
* isnan: Check if variable is NaN. Note that NaN == NaN is false!
* inv: inverse of a matrix
* sum: sum of all elements
* prod: product of all elements
* maximum,minimum: maximum,minimum value in an array
* max,min: maximum,minimum value of all arguments
* isnan: true if a value is NaN
* isinf: true if a value is Inf

These function can also operate of a given dimension: sum(array,dimension)

Find out more of these function by typing using the question mark symbol `?` followed by the function name. 

In [51]:
?plot

search: prevfloat partialsort partialsort! partialsortperm partialsortperm!

Couldn't find plot
Perhaps you meant splat, split, prod, dot, acot, cot, float, log, let or rsplit


No documentation found.

Binding `plot` does not exist.


In [52]:
apropos("sin")

Core.Compiler.Order.ord
Core.Compiler.from_interprocedural!
Core.Compiler.ir_inline_unionsplit!
Core.Compiler.ConstCallInfo
Core.Compiler.IRCode
Core.Compiler.AbstractIterationInfo
Core.Compiler.widenreturn_noslotwrapper
Core.Compiler.NotFound
Core.Compiler.JLTypeLattice
Core.Compiler.AbstractInterpreter
Core.Compiler.InferenceParams
Core.Compiler.canonicalize_typeassert!
Core.InterConditional
Core.Compiler.widenreturn
Core.Compiler.tmerge
Core.Compiler.adce_pass!
Core.Compiler.Effects
Core.Compiler.AbsIntStackUnwind
Core.Compiler.lock_mi_inference
Core.Compiler.Timings.Timing
Core.Compiler.EscapeAnalysis.compute_frameinfo
Core.Compiler.EscapeAnalysis.escape_exception!
Core.Compiler.EscapeAnalysis.EscapeInfo
Base
Base.:<
Base.IndexCartesian
Base.include_string
Base.names
Base.Colon
Core.NamedTuple
Base.repr
Base.skipmissing
Base.:>
Base.ENV
Base.any
Base.ismutabletype
Base.isprimitivetype
Base.splitprec
Core.String
Base.AbstractChannel
Base.chomp
Base.AbstractIrrational
Base.endswith
B

LibGit2.ProxyOptions
LibGit2.CheckoutOptions
LibGit2.treewalk
LibGit2.Callbacks
LibGit2.commit
LibGit2.GitCredential
LibGit2.content
LibGit2.GitAnnotated
LibGit2.revcount
LibGit2.push
LibGit2.count
LibGit2.merge!
LibGit2.restore
LibGit2.DiffFile
LibGit2.addfile
LibGit2.write!
LibGit2.push!
LibGit2.git_url
LibGit2.transact
LibGit2.Consts.GIT_PROXY
LibGit2.Consts.GIT_REBASE_OPERATION
REPL.TerminalMenus.RadioMenu
REPL.start_repl_backend
Base.MainInclude.Out
TOML.Parser
TOML.ParserError
Downloads.Downloader
Downloads.download
Pkg.PlatformEngines.register_auth_error_handler
Pkg.PlatformEngines.verify
Pkg.Resolve.enforce_optimality!
Pkg.REPLMode.Command
Pkg
Pkg.test
Pkg.add
Pkg.PackageSpec
Preferences
Preferences.main_uuid
Preferences.@set_preferences!
Preferences.@delete_preferences!
Preferences.set_preferences!
Preferences.process_sentinel_values!
libsodium_jll
ZeroMQ_jll
PrecompileTools
PrecompileTools.@recompile_invalidations
Sockets.send
ZMQ.Message
Parsers
Parsers.tryparse
Parsers.gets

In [53]:
using Statistics

In [54]:
?mean

search: mean mean! median median! SegmentationFault macroexpand @macroexpand



```
mean(itr)
```

Compute the mean of all elements in a collection.

!!! note
    If `itr` contains `NaN` or [`missing`](@ref) values, the result is also `NaN` or `missing` (`missing` takes precedence if array contains both). Use the [`skipmissing`](@ref) function to omit `missing` entries and compute the mean of non-missing values.


# Examples

```jldoctest
julia> using Statistics

julia> mean(1:20)
10.5

julia> mean([1, missing, 3])
missing

julia> mean(skipmissing([1, missing, 3]))
2.0
```

---

```
mean(f, itr)
```

Apply the function `f` to each element of collection `itr` and take the mean.

```jldoctest
julia> using Statistics

julia> mean(√, [1, 2, 3])
1.3820881233139908

julia> mean([√1, √2, √3])
1.3820881233139908
```

---

```
mean(f, A::AbstractArray; dims)
```

Apply the function `f` to each element of array `A` and take the mean over dimensions `dims`.

!!! compat "Julia 1.3"
    This method requires at least Julia 1.3.


```jldoctest
julia> using Statistics

julia> mean(√, [1, 2, 3])
1.3820881233139908

julia> mean([√1, √2, √3])
1.3820881233139908

julia> mean(√, [1 2 3; 4 5 6], dims=2)
2×1 Matrix{Float64}:
 1.3820881233139908
 2.2285192400943226
```

---

```
mean(A::AbstractArray; dims)
```

Compute the mean of an array over the given dimensions.

!!! compat "Julia 1.1"
    `mean` for empty arrays requires at least Julia 1.1.


# Examples

```jldoctest
julia> using Statistics

julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> mean(A, dims=1)
1×2 Matrix{Float64}:
 2.0  3.0

julia> mean(A, dims=2)
2×1 Matrix{Float64}:
 1.5
 3.5
```


# The file system

* On every current operating system, files are organized in a tree of directories starting from a root directory
* The absolute path of a directory or file defines which directories to follow starting from the root directory to the given directory or file
* In Linux/UNIX/Max OS X, files and directory names are separated by a forwardslash (`/`), on Windows by a backslash (`\` or `\\` if escaped) (but forwardslashes are allowed too)
* In order to avoid to deal with long path names, every program has a current working directory
* The current working directory from Julia can be queried with the command `pwd()`.
* The relative path of a directory or file defines which directories to follow starting from the current directory to the given directory or file
* In relative path, two dots (`..`) represent the parent directory.
* To change the current directory, you can use the command `cd`. For Linux and Mac OS X:

```julia
cd("/home/MyDir")
``` 

Under Windows you need to you the following:

```julia
cd("C:\\Users\\MyDir")
```

Note that here two backslashes are necessary ([why?](https://stackoverflow.com/questions/28328052/why-do-i-have-to-use-double-backslashes-for-file-paths-in-code)).

## NetCDF format
The reading/write of netCDF files is done using the [`NCDatasets`](https://github.com/Alexander-Barth/NCDatasets.jl) module, which is automatically installed with `DIVAnd`.      
You will find more information in the notebook [03-netCDF](03-netCDF.ipynb).

* Reading a variable called `var`  from a netCDF file

```julia
using NCDatasets
ds = Dataset("file.nc")
data = ds["var"][:];
close(ds)
```

* Writing a variable called `var` data to a netCDF file

```julia
ds = Dataset("file.nc","c")

# Define the dimension "lon" and "lat" with the size 100 and 110 resp.
defDim(ds,"lon",100)
defDim(ds,"lat",110)


# Define the variables temperature and salinity
v = defVar(ds,"temperature",Float32,("lon","lat"))
# write a the complete data set
v[:,:] = data
close(ds)
```

# Scripts

A script is a series of commands that can be collected in a script file.    
A script file has the extension `.jl`.

How can Julia find your script file?     
* it must be either in your current work directory
* the directory containing the script file must be added to the search path using `LOAD_PATH`. For example

```julia
push!(LOAD_PATH,"/some/path")
```

The code in a script is executed when using [`include`](https://docs.julialang.org/en/stable/base/base/#Base.include), which evaluates the contents of the input source file:

```julia-repl
include("filename.jl")
```

# Functions

Functions are similar to scripts.     
Unlike scripts, functions can have input/output parameters.    
For example a function calculating the speed of ocean current based on the zonal and meridional component

In [55]:
function current_speed(u,v)
   speed = sqrt(u^2 + v^2)
   return speed
end

current_speed (generic function with 1 method)

In [56]:
speed2 = current_speed(5,5)

7.0710678118654755

Another example of function: we compute naively the number of days without rain:

In [57]:
function dayswithoutrain(P)
    #....
    days = 0
    for i = 1 : length(P)
        # do something with i
        if P[i] == 0
            # count
            days = days+1
        end
        @show days
    end    
    return days
    
    # Note: what comes after the `return` is not exectuted
    print("The function has already finished")
end

dayswithoutrain (generic function with 1 method)

In [58]:
P = [0,0,0,3,4,5,3,0,0]
days = dayswithoutrain(P)    

days = 1
days = 2
days = 3
days = 3
days = 3
days = 3
days = 3
days = 4
days = 5


5

## Multiple dispatch
In Julia you can easily create a function that behaves differently, according to the type of input. Concretely, this is done by specifying the type of each input, using the `::` notation after the name of the function argument.    
Let's see with a very simple example that works on Strings but also on Floats.

In [59]:
function twice(word::String)
    return word * " " * word
end
function twice(aaa::Float64)
    return 2. * aaa
end

twice (generic function with 2 methods)

The output of the previous cell shows that the function has 2 methods (according to the type of input).

In [60]:
twice("bonjour"), twice(pi)

LoadError: MethodError: no method matching twice(::Irrational{:π})

Closest candidates are:
  twice(::Float64)
   @ Main In[59]:4
  twice(::String)
   @ Main In[59]:1


# Modules

Functions can be grouped into a module.      
The documentation describing how to create a module can be found at https://pkgdocs.julialang.org/v1/creating-packages/.


## Update module list

Before installing a module is it recommended to update the module list to ensure that the latest version of a module will be installed.

```julia
using Pkg
Pkg.update()
```

## Installation of modules

Packages can be install by using `Pkg.add` or by using the  Pkg REPL-mode entered from the Julia REPL using the key `]` (https://docs.julialang.org/en/stable/stdlib/Pkg/#Getting-Started-1).     
To install the package `DIVAnd` one should use for example:

```julia
using Pkg
Pkg.add("DIVAnd")
```

<div class="alert alert-block alert-info">
ℹ️ For some packages, one might need to follow specific installation instructions, which are usually available in the documentation of the corresponding package.
</div>


Module can also be installed directly from a repository:
```julia
Pkg.add("https://github.com/gher-uliege/DIVAnd.jl")
```

A module can be upgraded with:
```julia
using Pkg
Pkg.update("DIVAnd")
```

A no-longer used module can be removed with 
```julia
Pkg.rm("ModuleName")
```

The list of available packages is obtained as follows:

```julia
Pkg.status()
```

## Using modules

To access a function (e.g. the function `diva3d`) inside a module (e.g. `DIVAnd`), one needs to load the module with `using`. The following loads the module `DIVAnd`:

```julia
using DIVAnd
```

Now the function `diva3d` can be called.

# Dates
The [`Dates`](https://docs.julialang.org/en/v1/stdlib/Dates/index.html) module provides several functions to deal with date and time.

In [62]:
using Dates

## The DateTime and Date objects
Julia has a structure called `DateTime` to represent a date and time.

In [63]:
lastsecond = Dates.DateTime(1999,12,31,23,59,59)

1999-12-31T23:59:59

In [64]:
Today = Dates.today()
@show(Today, typeof(Today));

Today = Date("2024-09-13")
typeof(Today) = Date


The difference between two `DateTime` objects returns a structure representing the number of milliseconds.

In [65]:
dt = Dates.DateTime(2001,1,1) - Dates.DateTime(2000,1,1)

31622400000 milliseconds

In [66]:
@show typeof(dt)

typeof(dt) = Millisecond


Millisecond

The time difference can be converted into days:

In [67]:
Dates.Day(Dates.DateTime(2001,1,1) - Dates.DateTime(2000,1,1))

366 days

One can also add a duration to a date:

In [68]:
Dates.DateTime(2000,1,1) + Dates.Day(366), Dates.DateTime(2000,1,1) + Dates.Month(2)

(DateTime("2001-01-01T00:00:00"), DateTime("2000-03-01T00:00:00"))

Compute number of days before or after `now()`:

In [69]:
Dates.value(Dates.DateTime(2018,9,7) - Dates.now()) / 1000 / 60 / 60 / 24

-2198.6053304976854

In [70]:
Dates.value(Dates.DateTime(2017,9,7) - Dates.now()) /(24*60*60*1000)

-2563.605330902778

**Exercice:**     
Compute in how many days is your next birthday using the previous functions.

# Control Flow
## Loops
Let your computer do repetitive tasks!      
Loops have a counter which takes successively all elements of a row vector

In [71]:
for i = [1 2 10 20]
    @show i
end

i = 1
i = 2
i = 10
i = 20


Loops are often used with a range of values

In [72]:
for i = 1:5
    @show i
end

i = 1
i = 2
i = 3
i = 4
i = 5


Explicit loops can sometimes be avoided,     
for example, sum all integer from 1 to 10

In [73]:
total = 0;
for i = 1:10
   total = total + i;
end
total

55

Can simply be computed as `sum(1:10)`.

### Enumerate
When you want to loop over a list (containing strings for example) and need to count at the same time, you can use `enumerate`: 

In [74]:
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
for (pindex, planetname) in enumerate(planets)
    println("Planet #$(pindex): $(planetname)")
end

Planet #1: Mercury
Planet #2: Venus
Planet #3: Earth
Planet #4: Mars
Planet #5: Jupiter
Planet #6: Saturn
Planet #7: Uranus
Planet #8: Neptune


### Loop over dictionaries

In [75]:
capitals = Dict("Japan" => "Tokyo", "Afghanistan" => "Kabul", "Cyprus" => "Nicosia", "Somalia" => "Mogadishu")

for (country, capital) in capitals
    println("The capital of $(country) is $(capital)")
end

The capital of Somalia is Mogadishu
The capital of Afghanistan is Kabul
The capital of Japan is Tokyo
The capital of Cyprus is Nicosia


If you need to loop over the keys only:

In [76]:
for country in keys(capitals)
    println(country)
end

Somalia
Afghanistan
Japan
Cyprus


## if-statement

It is used when your code needs to behave differently depending on some conditions.       
It has the following structure.

```julia
if some_conditions
  # do something
else
  # do something else
end
```
The else section can be omitted.

For example.

```julia
if x < 0
   x = -x;
end
```

__Quiz:__ Which Julia function implements the last code example?

In [77]:
if Dates.dayname(Dates.dayofweek(Dates.today())) == "Friday"
   print("Have a nice weekend") 
end

Have a nice weekend

### Ternary operator
If statement can also be written in one line using the `?` operator:

In [79]:
isdir("../data/") ? @info("The data directory exists") : @warn("No data directory")

[ Info: The data directory exists
