# Introduction to Julia

Julia is a high-level programming language for technical computing which allows you to manipulate and analyse large data sets.

## Why Julia?
 * Julia is build from the ground for techical computing. 
 * The language is close to the mathematical notation, for example to define a function $f(x) = 2x + 3$ in Julia is:

```julia
f(x) = 2x + 3
```
  
 * Julia is free and open-source software.
 * Julia's code is compiled to machine code and loops can be as fast as in other compiled languages (like Fortran or C).


## Instructions for installing Julia on your laptop

1. Go to http://julialang.org/downloads/ and follow the instructions.
2. Install one editors with support for Julia (such as [Juno](http://junolab.org/), notepad++, emacs... or even vim).

### Ways to run Julia:

#### Command line

Tips:

* Use the `Tab` key to complete file, variable and function names
* `Up` and `down arrows` key to repeat a previously entered command
* `Control-R` to search a command
* On Windows enable "[quick edit](https://www.tekrevue.com/tip/boost-productivity-quickedit-mode-windows-command-prompt/)" for easier copy and pasting
![cmd](Images/julia-commandline.png)

#### Jupyter notebook (web-browser)

* Web-interface for Julia (among others)
* The Julia package `IJulia` which also installs Jupyter http://jupyter.org/
* Various [keyboard shortcuts](https://www.cheatography.com/weidadeyue/cheat-sheets/jupyter-notebook/) are defined to be productive with jupyter notebooks
* General documentation of [Jupyter Notebooks](http://jupyter-notebook.readthedocs.io)

![cmd](Images/julia-jupyter.png)

#### Juno

* Based on the Atom editor from GitHub
* Integrates an editor, command line and documentation browser
* Available from http://junolab.org/

![atom](Images/julia-atom.png)

http://localhost:8889/notebooks/1-Intro/02-Julia-introduction.ipynb## Julia documentation

* The manual: https://docs.julialang.org
* Tutorials and books: https://julialang.org/learning/


## Comparision with other languages

[Noteworthy Differences from other Languages](https://docs.julialang.org/en/stable/manual/noteworthy-differences/).

Julia is mostly influenced by MATLAB, but there are some siginificant differences.

### Differences from MATLAB
* Julia arrays are indexed with square brackets: `A[i,j]`.
* Julia arrays are assigned by reference. After `A=B`, changing elements of `B` will modify `A` as well. If you need to copy an array, use `b = copy(a)`.
* Julia function parameters are passed and assigned by reference. If a function modifies an array, the changes will be visible in the caller.
* A bang (!) indicates if a function changes one of its argument
* In Julia, parentheses must be used to call a function with zero arguments, like in `tic()` and `toc()`.
* Julia's single quotes enclose characters, not strings.
* Julia does not automatically grow arrays in an assignment statement. 
* Scope of variables in a loop is local: 

```julia
   for i = 1:10
        z = i
   end
```

  will result in undefined z after the loop unless defined before the loop 
* In MATLAB, ranges are sometimes enclosed with brackets, e.g. `[1:10]`. This is also valid Julia code, but it generates a vector whose single element is a range from 1 to 10. To declare a range in Julia, simply use `1:10` without the brackets.

### Differences from Python
* Julia requires `end` keyword to end a block (loop, condition, ...).
* In Julia, indexing of arrays, strings, etc. is 1-based not 0-based.
* Julia's slice indexing includes the last element, unlike in Python. `a[2:3]` in Julia is `a[1:3]` in Python.
* Julia does not support negative indexes. In particular, the last element of a list or array is indexed with `end` in Julia, not `-1` as in Python.

[MATLAB–Python–Julia cheatsheet](https://cheatsheets.quantecon.org/)

* Julia is compiled
   * For loop are fast, but
   * Loading modules is slower than in other languages
   * Sometimes Julia needs to be restarted (in IJulia the kernel needs to be restarted) when e.g. a module is changed.

# First steps in Julia

## Numbers

* Use a dot (.) as decimal separator (e.g. 3.14 and not 3,14)
* You can use the scientific notation $a \times 10^{-b}$ using the e-notation. (e.g. $3 \times10^{-7}$ becomes 3e-7) 
* Use Julia as a calculator:

In [1]:
3e-7

3.0e-7

In [2]:
4/2

2.0

In [3]:
1 + 3 * 4/2 

7.0

The usual operator precedence applies.

## Useful constants

Various constants are also pre-defined:     
π: pi (3.141592...)     
e: Euler's number (2.7182818...)     
im: the imaginary number (im² = -1)     
Inf (Infinity, result from e.g. 1/0) and     
NaN (Not a Number - result from e.g. 0/0).

**Examples:**

In [4]:
π 

π = 3.1415926535897...

[*Euler's identity*](https://en.wikipedia.org/wiki/Euler%27s_identity) (should be -1):

In [5]:
exp(-im * π)

-1.0 - 1.2246467991473532e-16im

## Variables

* Numbers (and any other data type) can be put into variables
* The value of a variable is referenced by its name
* A variable name can be composed by letters (a-z and A-Z, including greek letters, accents,...), numbers (0-9), underscore (_) and some unicode symbols (like greek letters). The first character cannot be a number.

**Example:**

In [6]:
temp = 21

21

This one is not valid (starts with a digits):
```julia
2temp = 1.
```

Produces the error:
```
syntax: "2" is not a valid function argument name
```



To see the content of the variable `temp`, use the [`@show`](https://docs.julialang.org/en/latest/base/base/#Base.@show) macro:

In [7]:
@show temp;

temp = 21


Any expression can now include the variable `temp`:

In [8]:
2 * temp

42

* The variable `temp` has now the value 21. The value of the variable can be changed later on.
* An assignment without a final semicolon echoes its value to the screen
* Careful: the value of constants can be overwritten. The following is allowed but not encouraged:
    	
```julia        
    pi = 3; # do not do this
```
* However, if you explicitely define a variable as a constant, trying to modify it will result in a warning.

In [9]:
const kb = 1.38064852e-23
kb = 1.38e-23

1.38e-23

The command [`varinfo()`](https://docs.julialang.org/en/stable/stdlib/InteractiveUtils/#InteractiveUtils.varinfo) lists the currently defined variables and the loaded modules, as well as their size in a markdown table.

In [10]:
varinfo()

| name |    size | summary |
|:---- | -------:|:------- |
| Base |         | Module  |
| Core |         | Module  |
| Main |         | Module  |
| kb   | 8 bytes | Float64 |
| temp | 8 bytes | Int64   |


The command [`typeof()`](https://docs.julialang.org/en/stable/base/base/#Core.typeof) returns the type of a variable:

In [11]:
typeof(temp)

Int64

## Strings
They are delimited by double quotes:

In [12]:
s = "Hello world"
print(s);

Hello world

How to use a double quote in a string?      
→ place a backslash `\` before it:

In [13]:
s = "The letter \"A\" is the first letter of the alphabet."
print(s)

The letter "A" is the first letter of the alphabet.

## Symbols

* A symbol is an [interned string](https://en.wikipedia.org/wiki/String_interning) identifier which means that every string symbol is replaced internally by a number
* This makes comparison between symbols faster than comparison between strings
* Symbols are also used in metaprogramming (julia code which produces julia code).

In [68]:
:mysymbol

:mysymbol

In [69]:
typeof(:mysymbol)

Symbol

## Vectors and matrices
The module [`LinearAlgebra`](https://docs.julialang.org/en/stable/stdlib/LinearAlgebra/) provides useful linear algebra operations.

In [70]:
using LinearAlgebra

Vectors are list of numbers. The column vector $\left(\begin{array}{c}1 \\ 2 \\ 3 \end{array} \right)$ is represented by:

In [16]:
[1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

Matrices are tables of numbers. Rows are separated by a semicolon. The matrix 
$\left(\begin{array}{cc}1 & 2 \\ 3 & 4 \end{array} \right)$ is represented by:

In [17]:
[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

### Ranges

Consecutive elements can be written as:

    `first:step:last`
    
or simply, if the step is 1,
    	
    `first:last`
    
Use the function [`collect`](https://docs.julialang.org/en/stable/base/collections/#Base.collect-Tuple{Type,Any}) or `[first:step:last;]` to transform a range into a vector:
   
Instead of typing this:  

In [18]:
[1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

one could simply write this as:

In [19]:
1:5

1:5

Now if we need only every second element:

In [20]:
1:2:6

1:2:5

Note that 6 is not part of the previous range.

## Indexing

Consider the following vector:

In [21]:
a = [2,5,7,19,2]

5-element Array{Int64,1}:
  2
  5
  7
 19
  2

* Individual elements of a vector or matrix can be addressed by their index using square brackets.
* The second element of a vector `a` is for example `a[2]`

The special word `end` refers to the last index.     
`end` is also useful to refer to elements with respect to the last one:

In [22]:
a[end]

2

In [23]:
a[end-2]

7

One can also use a list of indexes to extract a part of the vector

In [24]:
a[[2,3,4]]
# a[2,3,4] would mean we want to access the (single) index [2, 3, 4]

3-element Array{Int64,1}:
  5
  7
 19

Or simply:

In [25]:
a[2:4]

3-element Array{Int64,1}:
  5
  7
 19

The symbol colon **:** is a short-hand for 1:end

## Matrix indexing

* For matrices, two indices are generally used.
* The element at the second row and the first column of a matrix A is for example `A[2,1]`

In [26]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [27]:
A[2,1]

3

In [28]:
A[:,2]

2-element Array{Int64,1}:
 2
 4

Julia supports also higher-dimensional arrays and indexing works similarily.

## Additional data structures

### Dictionaries

A dictionary [`Dict`](https://docs.julialang.org/en/v1/base/collections/index.html#Dictionaries-1) is a data structure that maps keys to values.      
**Example:**

In [29]:
data = Dict("Temperature" => 20.23, "Salinity" => 37.54)

Dict{String,Float64} with 2 entries:
  "Temperature" => 20.23
  "Salinity"    => 37.54

Dictionaries are useful to retrieve an entry using the key:

In [30]:
data["Temperature"]

20.23

### Tuple

* A tuple is a (usually short) sequence of values (those values can be of any type)
* A tuple cannot be modified (e.g. you cannot add another element to a tuple or replace an existing element)
* Tuples are less flexible, but more efficient than vectors
* A tuple is enclosed with a round parentesis, e.g. `(12,45,"a string")` or `(42,)` (here the last comma is necessary to distinguish between a parentesis enclosing a tuple and parentesis grouping an expression)

In [31]:
liegeCoordinates = (50.633333, 5.566667)
@show typeof(liegeCoordinates);

typeof(liegeCoordinates) = Tuple{Float64,Float64}


We cannot change the values: tuples are immutable!
you will see the error

```julia
liegeCoordinates[1] =  50.7



MethodError: no method matching setindex!(::Tuple{Float64,Float64}, ::Float64, ::Int64)
```

Tuples are typically used for output arguments (and sometimes for input arguments too)     
We'll come back to functions later in this notebook:

In [32]:
function myfunction(a,b,the_rest...)
    return (a+1,b+2,sum(the_rest))
end

p1,p2,p3 = myfunction(1,2,3,4)

@show p1
@show p2
@show p3

p1 = 2
p2 = 4
p3 = 7


7

In [33]:
all_p =  myfunction(1,2,3,4)

@show all_p;
@show typeof(all_p);

all_p = (2, 4, 7)
typeof(all_p) = Tuple{Int64,Int64,Int64}


# Operators

* Scalar and matrix operations: **+** sum, **-** difference, __*__ multiplication, **/** division
* Element-wise matrix operations: __.*__ multiply element-wise, __./__ divide element-wise 

## Comparison operators

equal (`==`) and different (`!=`) 

In [34]:
2 == 1

false

In [35]:
9 == 3*3

true

The dot is used for element-wise comparisons:

In [36]:
[1 2 3] == [1 3 2]

false

In [37]:
[1 2 3] .== [1 3 2]

1×3 BitArray{2}:
 1  0  0

Be aware of the limited precision of floating point numbers

In [38]:
2.0000000000000001 == 2

true

Element-wise different (`.!=`)

In [39]:
[1 2 3] .!= [3 2 1]

1×3 BitArray{2}:
 1  0  1

Comparision between numbers: <, >, <= (≤), => (≥)

In [40]:
30 > 25

true

Element-wise comparision between vector and matrices: .<, .>, .<= (.≤), .=> (.≥)

In [41]:
[1,2,3] .> 2

3-element BitArray{1}:
 0
 0
 1

In [42]:
[1,2,3] .> [3,1,2]

3-element BitArray{1}:
 0
 1
 1

Logical "and" (&&) logical "or" (||) (with short-circuit evaluation)

In [43]:
temperature = 30;
precipitation = 10;

if temperature > 25 && precipitation == 0
    print("go outside!")
else
    print("stay in and code")
end

stay in and code

* logical element-wise "and" (.&) logical element-wise "or" (.|)

* The results of such operators can also be used to index an array
    
* For example return all elements in the variable T which are greater than 10 but less than 20.
    

In [44]:
T = [27,17,20,26,32]
T[20 .< T .& T .< 30]

2-element Array{Int64,1}:
 27
 26

In [45]:
T .< 30

5-element BitArray{1}:
 1
 1
 1
 1
 0

# Useful functions

* sin, cos, tan: trigonometric functions
* asin, acos, atan: inverse trigonometric functions
* log, log2, log10: natural, base 2 and base 10 logarithms: 
* exp: exponentiation
* abs: absolute value
* sqrt: square root
* mean: mean
* median: median
* std: standard deviation
* var: variance
* mod: modulo (useful to manipulate e.g. the longitude)
* isnan: Check if variable is NaN. Note that NaN == NaN is false!
* inv: inverse of a matrix
* sum: sum of all elements
* prod: product of all elements
* maximum,minimum: maximum,minimum value in an array
* max,min: maximum,minimum value of all arguments
* isnan: true if a value is NaN
* isinf: true if a value is Inf

These function can also operate of a given dimension: sum(array,dimension)

Find out more of these function by typing ? followed by the function name. 

In [46]:
?open

search: open isopen propertynames ZeroPivotException CompositeException operm



```
open(f::Function, args...; kwargs....)
```

Apply the function `f` to the result of `open(args...; kwargs...)` and close the resulting file descriptor upon completion.

# Examples

```jldoctest
julia> open("myfile.txt", "w") do io
           write(io, "Hello world!")
       end;

julia> open(f->read(f, String), "myfile.txt")
"Hello world!"

julia> rm("myfile.txt")
```

---

```
open(filename::AbstractString; lock = true, keywords...) -> IOStream
```

Open a file in a mode specified by five boolean keyword arguments:

| Keyword    | Description            | Default                               |
|:---------- |:---------------------- |:------------------------------------- |
| `read`     | open for reading       | `!write`                              |
| `write`    | open for writing       | `truncate \| append`                  |
| `create`   | create if non-existent | `!read & write \| truncate \| append` |
| `truncate` | truncate to zero size  | `!read & write`                       |
| `append`   | seek to end            | `false`                               |

The default when no keywords are passed is to open files for reading only. Returns a stream for accessing the opened file.

The `lock` keyword argument controls whether operations will be locked for safe multi-threaded access.

!!! compat "Julia 1.5"
    The `lock` argument is available as of Julia 1.5.


---

```
open(filename::AbstractString, [mode::AbstractString]; lock = true) -> IOStream
```

Alternate syntax for open, where a string-based mode specifier is used instead of the five booleans. The values of `mode` correspond to those from `fopen(3)` or Perl `open`, and are equivalent to setting the following boolean groups:

| Mode | Description                   | Keywords                       |
|:---- |:----------------------------- |:------------------------------ |
| `r`  | read                          | none                           |
| `w`  | write, create, truncate       | `write = true`                 |
| `a`  | write, create, append         | `append = true`                |
| `r+` | read, write                   | `read = true, write = true`    |
| `w+` | read, write, create, truncate | `truncate = true, read = true` |
| `a+` | read, write, create, append   | `append = true, read = true`   |

The `lock` keyword argument controls whether operations will be locked for safe multi-threaded access.

# Examples

```jldoctest
julia> io = open("myfile.txt", "w");

julia> write(io, "Hello world!");

julia> close(io);

julia> io = open("myfile.txt", "r");

julia> read(io, String)
"Hello world!"

julia> write(io, "This file is read only")
ERROR: ArgumentError: write failed, IOStream is not writeable
[...]

julia> close(io)

julia> io = open("myfile.txt", "a");

julia> write(io, "This stream is not read only")
28

julia> close(io)

julia> rm("myfile.txt")
```

!!! compat "Julia 1.5"
    The `lock` argument is available as of Julia 1.5.


---

```
open(fd::OS_HANDLE) -> IO
```

Take a raw file descriptor wrap it in a Julia-aware IO type, and take ownership of the fd handle. Call `open(Libc.dup(fd))` to avoid the ownership capture of the original handle.

!!! warn
    Do not call this on a handle that's already owned by some other part of the system.


---

```
open(command, mode::AbstractString, stdio=devnull)
```

Run `command` asynchronously. Like `open(command, stdio; read, write)` except specifying the read and write flags via a mode string instead of keyword arguments. Possible mode strings are:

| Mode | Description | Keywords                    |
|:---- |:----------- |:--------------------------- |
| `r`  | read        | none                        |
| `w`  | write       | `write = true`              |
| `r+` | read, write | `read = true, write = true` |
| `w+` | read, write | `read = true, write = true` |

---

```
open(command, stdio=devnull; write::Bool = false, read::Bool = !write)
```

Start running `command` asynchronously, and return a `process::IO` object.  If `read` is true, then reads from the process come from the process's standard output and `stdio` optionally specifies the process's standard input stream.  If `write` is true, then writes go to the process's standard input and `stdio` optionally specifies the process's standard output stream. The process's standard error stream is connected to the current global `stderr`.

---

```
open(f::Function, command, args...; kwargs...)
```

Similar to `open(command, args...; kwargs...)`, but calls `f(stream)` on the resulting process stream, then closes the input stream and waits for the process to complete. Returns the value returned by `f`.


In [47]:
apropos("mean")

Base.isbitstype
Base.IteratorSize
Base.IndexLinear
Base.@nospecialize
Base.nextind
Base.:∘
Base.isequal
Base.isconcretetype
Base.prevind
Base.:*
Base.@pure
Base.IteratorEltype
Base.Condition
Base.LOAD_PATH
Base.Slice
Base.RangeStepStyle
Base.isbitsunion
Base.reduce
Base.IndexCartesian
Base.isdispatchtuple
Base.Multimedia.display
Base.IRShow.compute_ir_line_annotations
Base.Broadcast.newindex
Base.Sys.isbsd
Base.Threads.atomic_cas!
Base.CoreLogging.@info
Base.CoreLogging.@debug
Base.CoreLogging.@error
Base.CoreLogging.@warn
Base.CoreLogging.@logmsg
Base.sortperm
Base.Sort.partialsortperm
Base.Experimental.register_error_hint
LibGit2.isbare
LibGit2.treewalk
LibGit2.clone
LibGit2.DiffOptionsStruct
LibGit2.BlameOptions
Profile.fetch
Base.randn
Random.randn!
LinearAlgebra.ZeroPivotException
Base.sqrt
LinearAlgebra.LAPACK.gesvx!
SparseArrays.sprand
Test.@testset
Test.test_expr!
Statistics.var
Statistics.mean!
Statistics.stdm
Statistics.mean
Statistics.varm
Statistics.median
Statistics.middle

In [48]:
using Statistics

In [49]:
?mean

search: mean mean! median median! SegmentationFault macroexpand @macroexpand



```
mean(itr)
```

Compute the mean of all elements in a collection.

!!! note
    If `itr` contains `NaN` or [`missing`](@ref) values, the result is also `NaN` or `missing` (`missing` takes precedence if array contains both). Use the [`skipmissing`](@ref) function to omit `missing` entries and compute the mean of non-missing values.


# Examples

```jldoctest
julia> using Statistics

julia> mean(1:20)
10.5

julia> mean([1, missing, 3])
missing

julia> mean(skipmissing([1, missing, 3]))
2.0
```

---

```
mean(f::Function, itr)
```

Apply the function `f` to each element of collection `itr` and take the mean.

```jldoctest
julia> using Statistics

julia> mean(√, [1, 2, 3])
1.3820881233139908

julia> mean([√1, √2, √3])
1.3820881233139908
```

---

```
mean(f::Function, A::AbstractArray; dims)
```

Apply the function `f` to each element of array `A` and take the mean over dimensions `dims`.

!!! compat "Julia 1.3"
    This method requires at least Julia 1.3.


```jldoctest
julia> using Statistics

julia> mean(√, [1, 2, 3])
1.3820881233139908

julia> mean([√1, √2, √3])
1.3820881233139908

julia> mean(√, [1 2 3; 4 5 6], dims=2)
2×1 Array{Float64,2}:
 1.3820881233139908
 2.2285192400943226
```

---

```
mean(A::AbstractArray; dims)
```

Compute the mean of an array over the given dimensions.

!!! compat "Julia 1.1"
    `mean` for empty arrays requires at least Julia 1.1.


# Examples

```jldoctest
julia> using Statistics

julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> mean(A, dims=1)
1×2 Array{Float64,2}:
 2.0  3.0

julia> mean(A, dims=2)
2×1 Array{Float64,2}:
 1.5
 3.5
```


# The file system

* On every current operating system, files are organized in a tree of directories starting from a root directory
* The absolute path of a directory or file defines which directories to follow starting from the root directory to the given directory or file
* In Linux/UNIX/Max OS X, files and directory names are separated by a forwardslash (`/`), on Windows by a backslash (`\` or `\\` if escaped) (but forwardslashes are allowed too)
* In order to avoid to deal with long path names, every program has a current working directory
* The current working directory from Julia can be queried with the command `pwd()`.
* The relative path of a directory or file defines which directories to follow starting from the current directory to the given directory or file
* In relative path, two dots (`..`) represent the parent directory.
* To change the current directory, you can use the command `cd`. For Linux and Mac OS X:

```julia
cd("/home/MyDir")
``` 

Under Windows you need to you the following:

```julia
cd("C:\\Users\\MyDir")
```

Note that here two backslashes are necessary ([why?](https://stackoverflow.com/questions/28328052/why-do-i-have-to-use-double-backslashes-for-file-paths-in-code)).

## NetCDF format
The reading/write of netCDF files is done using the [`NCDatasets`](https://github.com/Alexander-Barth/NCDatasets.jl) module, which is automatically installed with `DIVAnd`.
You can also find more information in the notebook [03-netCDF](03-netCDF.ipynb).

* Reading a variable called `var`  from a netCDF file

```julia
using NCDatasets
ds = Dataset("file.nc")
data = ds["var"][:];
close(ds)
```

* Writing a variable called `var` data to a netCDF file

```julia
ds = Dataset("file.nc","c")

# Define the dimension "lon" and "lat" with the size 100 and 110 resp.
defDim(ds,"lon",100)
defDim(ds,"lat",110)


# Define the variables temperature and salinity
v = defVar(ds,"temperature",Float32,("lon","lat"))
# write a the complete data set
v[:,:] = data
close(ds)
```

# Scripts

A script is a series of commands that can be collected in a script file.    
A script file has the extension `.jl`.

How can Julia find your script file?     
* it must be either in your current work directory
* the directory containing the script file must be added to the search path using `LOAD_PATH`. For example

```julia
push!(LOAD_PATH,"/some/path")
```

The code in a script is executed when using [`include`](https://docs.julialang.org/en/stable/base/base/#Base.include), which evaluates the contents of the input source file:

```
include("filename.jl")
```

# Functions

Functions are similar to scripts.     
Unlike scripts, functions can have input/output parameters.    
For example a function calculating the speed of ocean current based on the zonal and meridional component

In [50]:
function current_speed(u,v)
   speed = sqrt(u^2 + v^2)
   return speed
end

current_speed (generic function with 1 method)

In [51]:
speed2 = current_speed(5,5)

7.0710678118654755

Another example of function: we compute naively the number of days without rain:

In [52]:
function dayswithoutrain(P)
    #....
    days = 0
    for i = 1 : length(P)
        # do something with i
        if P[i] == 0
            # count
            days = days+1
        end
        @show days
    end    
    return days
    
    # Note: what comes after the `return` is not exectuted
    print("The function has already finished")
end

dayswithoutrain (generic function with 1 method)

In [53]:
P = [0,0,0,3,4,5,3,0,0]
days = dayswithoutrain(P)    

days = 1
days = 2
days = 3
days = 3
days = 3
days = 3
days = 3
days = 4
days = 5


5

# Modules

Functions can be grouped into a module. 


## Update module list

Before installing a module is it recommended to update the module list to ensure that the latest version of a module will be installed.

```julia
using Pkg
Pkg.update()
```

## Installation of modules

Packages can be install by using `Pkg.add` or by using the  Pkg REPL-mode entered from the Julia REPL using the key `]` (https://docs.julialang.org/en/stable/stdlib/Pkg/#Getting-Started-1).     
To install the package `PyPlot` one should use for example:

```julia
using Pkg
Pkg.add("PyPlot")
```

Note, for some packages one might need to follow specific installation instructions which are usually available in the documentation of the corresponding package (e.g. https://github.com/JuliaPy/PyPlot.jl ).

Module can also be installed directly from a repository:

```julia
Pkg.add("https://github.com/gher-ulg/DIVAnd.jl")
```

A module can be upgraded with:
```julia
using Pkg
Pkg.update("PyPlot")
```

A no-longer used module can be removed with `Pkg.rm("ModuleName")`.     
The list of available packages is obtained as follows:

```julia
Pkg.status()
```

## Using modules

To access a function (e.g. the function `plot`) inside a module (e.g. `PyPlot`), one needs to load the module with `using`. The following loads the module `PyPlot`:

```julia
using PyPlot
```

Now the function `plot` can be called.

In [54]:
using PyPlot

┌ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
└ @ Base loading.jl:1278
┌ Warning: `@get!(dict, key, default)` at /home/ctroupin/.julia/packages/MacroTools/jYLA1/src/utils.jl:176 is deprecated, use `get!(()->default, dict, key)` instead.
└ @ Base deprecated.jl:204
┌ Warning: `@get!(dict, key, default)` at /home/ctroupin/.julia/packages/MacroTools/jYLA1/src/utils.jl:197 is deprecated, use `get!(()->default, dict, key)` instead.
└ @ Base deprecated.jl:204


# Dates
The [`Dates`](https://docs.julialang.org/en/v1/stdlib/Dates/index.html) module provides several functions to deal with date and time.

In [55]:
using Dates

Julia has a structure called `DateTime` to represent a date and time.

In [56]:
lastsecond = Dates.DateTime(1999,12,31,23,59,59)

1999-12-31T23:59:59

The difference between two `DateTime`s returns a structure representing the number of milliseconds.

In [57]:
Dates.DateTime(2001,1,1)

2001-01-01T00:00:00

In [58]:
dt = Dates.DateTime(2001,1,1) - Dates.DateTime(2000,1,1)

31622400000 milliseconds

In [59]:
@show typeof(dt)

typeof(dt) = Millisecond


Millisecond

The time difference can be converted into days:

In [60]:
Dates.Day(Dates.DateTime(2001,1,1) - Dates.DateTime(2000,1,1))

366 days

Add a duration to a date

In [61]:
Dates.DateTime(2000,1,1) + Dates.Day(366)

2001-01-01T00:00:00

Compute number of days before or after `now()`:

In [62]:
Dates.value(Dates.DateTime(2018,9,7) - Dates.now()) / 1000 / 60 / 60 / 24

-697.4549952662037

In [63]:
Dates.value(Dates.DateTime(2017,9,7) - Dates.now()) /(24*60*60*1000)

-1062.4549984027778

**Exercice:**     
Compute in how many days is your next birthday using the previous functions.

# Control Flow
## Loops
Let your computer do repetitive tasks!      
Loops have a counter which takes successively all elements of a row vector

In [64]:
for i = [1 2 10 20]
    @show i
end

i = 1
i = 2
i = 10
i = 20


Loops are often used with a range of values

In [65]:
for i = 1:5
    @show i
end

i = 1
i = 2
i = 3
i = 4
i = 5


Explicit loops can sometimes be avoided,     
for example, sum all integer from 1 to 10

In [66]:
total = 0;
for i = 1:10
   total = total + i;
end
total

55

Can simply be computed as `sum(1:10)`.

# if-statement

* Sometimes your code needs to behave differently depending on some conditions.

* if-statement has the following structure.

```julia
if some_conditions
  # do something
else
  # do something else
end
```
The else section can be omitted.

For example.

```julia
if x < 0
   x = -x;
end
```

__Quiz:__ Which Julia function implements the last code example?

In [67]:
if Dates.dayname(Dates.dayofweek(Dates.today())) == "Friday"
   print("Have a nice weekend") 
end